import { watch } from 'node:fs';
import { builtinModules } from 'node:module';
import { join } from 'node:path';

import manifest from '../manifest.json' with { type: 'json' };

/**
 * Bundle the plugin into a single CommonJS `main.js`.
 *
 * Obsidian loads plugins with its own CommonJS loader, so the output format is
 * `cjs` regardless of this package being `"type": "module"` — Obsidian never
 * reads package.json. The externals below are modules the app already provides
 * at runtime; bundling a second copy of `@codemirror/state` in particular
 * breaks the editor in ways that are very hard to trace back here.
 */
const external = [
  'obsidian',
  'electron',
  '@codemirror/autocomplete',
  '@codemirror/collab',
  '@codemirror/commands',
  '@codemirror/language',
  '@codemirror/lint',
  '@codemirror/search',
  '@codemirror/state',
  '@codemirror/view',
  '@lezer/common',
  '@lezer/highlight',
  '@lezer/lr',
  ...builtinModules,
  ...builtinModules.map((name) => `node:${name}`),
];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY BUN
If you want to view the source, please visit the GitHub repository of this plugin.
*/`;

const production = Bun.argv.includes('--production');
const watching = Bun.argv.includes('--watch');

/**
 * Where the build lands.
 *
 * Point `OBSIDIAN_PLUGIN_DIR` at `<dev vault>/.obsidian/plugins/copy-as-prompt`
 * and the watch build writes straight into the vault. Never use your real
 * vault for this.
 */
const outdir = (!production && Bun.env['OBSIDIAN_PLUGIN_DIR']) || '.';

async function build(): Promise<boolean> {
  try {
    return await bundle();
  } catch (error) {
    // Bun.build throws — rather than returning success: false — when an import
    // cannot be resolved. In watch mode that is usually a file mid-rename, so
    // report it and keep watching instead of exiting and leaving you wondering
    // why saves stopped rebuilding.
    console.error(error instanceof Error ? error.message : error);

    return false;
  }
}

async function bundle(): Promise<boolean> {
  const result = await Bun.build({
    entrypoints: ['./src/main.ts'],
    outdir,
    naming: { entry: 'main.js' },
    format: 'cjs',
    target: 'browser',
    external,
    banner,
    sourcemap: production ? 'none' : 'inline',
    minify: production,
    define: { 'process.env.NODE_ENV': JSON.stringify(production ? 'production' : 'development') },
  });

  for (const log of result.logs) console.error(log);

  return result.success;
}

/**
 * Copy the static plugin files next to `main.js`.
 *
 * Obsidian reads `manifest.json` and `styles.css` from the plugin folder, so a
 * vault-targeted build needs them there too. `.hotreload` is the marker the
 * Hot-Reload plugin looks for.
 */
async function copyStaticFiles(): Promise<void> {
  if (outdir === '.') return;

  await Bun.write(join(outdir, 'manifest.json'), Bun.file('manifest.json'));
  await Bun.write(join(outdir, 'styles.css'), Bun.file('styles.css'));
  await Bun.write(join(outdir, '.hotreload'), '');
}

const succeeded = await build();
await copyStaticFiles();

if (!watching) {
  console.log(
    succeeded
      ? `Built ${manifest.id} ${manifest.version} → ${join(outdir, 'main.js')}`
      : 'Build failed.',
  );
  process.exit(succeeded ? 0 : 1);
}

console.log(`Watching src/ → ${join(outdir, 'main.js')}`);

// Bun.build has no watch mode of its own, and `bun --watch` only re-runs when
// a file this script imports changes — which src/ is not. So watch src/ here.
let pending: ReturnType<typeof setTimeout> | undefined;

async function rebuild(): Promise<void> {
  console.log((await build()) ? 'Rebuilt.' : 'Rebuild failed.');
}

watch('./src', { recursive: true }, () => {
  // Editors write a file in several syscalls, so a single save fires more than
  // one event. Debounce, or every save triggers a handful of redundant builds.
  clearTimeout(pending);
  pending = setTimeout(() => void rebuild(), 50);
});
